export const Stock = [
  {
    id: "1",
    nombre: "Guitarra Lore ",
    descripcion: "lorem algo",
    precio: 1500,
    img: "../../../public/imagenes/guitarra_01.jpg",
    stock: 5,
  },
  {
    id: "2",
    nombre: "Guitarra Lies",
    descripcion: "lorem algo",
    precio: 1500,
    img: "../../../public/imagenes/guitarra_02.jpg",
    stock: 5,
  },
  {
    id: "3",
    nombre: "Guitarra True",
    descripcion: "lorem algo",
    precio: 1500,
    img: "../../../public/imagenes/guitarra_03.jpg",
    stock: 5,
  },
  {
    id: "4",
    nombre: "Guitarra Scream",
    descripcion: "lorem algo",
    precio: 1500,
    img: "../../../public/imagenes/guitarra_04.jpg",
    stock: 5,
  },
  {
    id: "5",
    nombre: "Guitarra Hell",
    descripcion: "lorem algo",
    precio: 1500,
    img: "../../../public/imagenes/guitarra_05.jpg",
    stock: 5,
  },
];
